services:
  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-hexabase}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_HOST_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-hexabase}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hexabase

  # Redis cache
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_HOST_PORT:-6380}:6379"
    volumes:
      - redis_data:/data
    networks:
      - hexabase

  # NATS message queue
  nats:
    image: nats:2.10-alpine
    ports:
      - "${NATS_HOST_PORT:-4223}:4222"
      - "${NATS_MONITOR_PORT:-8223}:8222"
    command: ["--jetstream", "--store_dir=/data"]
    volumes:
      - nats_data:/data
    networks:
      - hexabase

  # API Server
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${API_HOST_PORT:-8080}:8080"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DBNAME=hexabase
      - DATABASE_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NATS_URL=nats://nats:4222
      - AUTH_JWT_SECRET=dev-jwt-secret-change-in-production
      - STRIPE_SECRET_KEY=sk_test_your_key_here
      - STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret
      - GIN_MODE=debug
    depends_on:
      - postgres
      - redis
      - nats
    networks:
      - hexabase
    volumes:
      - ./api/config.yaml:/root/config.yaml:ro

  # Worker
  worker:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ["./worker"]
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DBNAME=hexabase
      - DATABASE_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NATS_URL=nats://nats:4222
      - AUTH_JWT_SECRET=dev-jwt-secret-change-in-production
    depends_on:
      - postgres
      - redis
      - nats
    networks:
      - hexabase
    volumes:
      - ./api/config.yaml:/root/config.yaml:ro

  migrate:
    image: migrate/migrate:4
    profiles:
      - tools
    volumes:
      - ./api/internal/shared/db/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-hexabase}?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hexabase

volumes:
  postgres_data:
  redis_data:
  nats_data:

networks:
  hexabase:
    driver: bridge