apiVersion: v1
kind: Namespace
metadata:
  name: ai-ops-llm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama
  namespace: ai-ops-llm
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ollama
  namespace: ai-ops-llm
  labels:
    app: ollama
spec:
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      serviceAccountName: ollama
      # Run on nodes specifically designated for LLM workloads
      nodeSelector:
        node-role: private-llm
      tolerations:
        - key: "private-llm"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: ollama
          image: ollama/ollama:latest
          # For GPU support, you would add resource requests/limits for nvidia.com/gpu
          # and ensure the nodes have the NVIDIA device plugin installed.
          # resources:
          #   requests:
          #     nvidia.com/gpu: 1
          #   limits:
          #     nvidia.com/gpu: 1
          ports:
            - containerPort: 11434
              name: http
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
      volumes:
        - name: ollama-data
          hostPath:
            path: /var/lib/ollama # Persists models on the host node
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ai-ops-llm
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
