# Flux GitOps Configuration for Hexabase KaaS
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: hexabase-kaas
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/hexabase/k8s-manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hexabase-kaas
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: hexabase-kaas
  validation: client
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets