# Default values for hks-observability-agents.

# -- Tenant specific configuration
tenant:
  # workspaceId is a unique identifier for the tenant workspace.
  # This value MUST be provided during installation. It will be added as an external label
  # to all metrics and logs to ensure data isolation in the multi-tenant central stack.
  workspaceId: ""

# -- Configuration for the central observability stack that agents will send data to.
# These values are injected by the Hexabase control plane during deployment.
centralObservability:
  prometheus:
    # remoteWriteUrl is the URL of the central Prometheus remote_write endpoint.
    remoteWriteUrl: "http://prometheus.hexabase-system.svc.cluster.local:9090/api/v1/write"
  loki:
    # lokiUrl is the URL of the central Loki push endpoint.
    lokiUrl: "http://loki.hexabase-system.svc.cluster.local:3100/loki/api/v1/push"

# -- Configuration for the Prometheus Agent (based on prometheus-agent chart)
prometheusAgent:
  # -- Enable or disable the Prometheus Agent deployment.
  enabled: true
  image:
    repository: prom/prometheus
    tag: v2.47.2
    pullPolicy: IfNotPresent
  # -- Scrape interval for collecting metrics.
  scrapeInterval: "30s"
  # -- Additional scrape configurations can be added here.
  # For example, to scrape all pods with the 'scrape=true' annotation.
  extraScrapeConfigs: |
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true

# -- Configuration for Promtail (based on promtail chart)
promtail:
  # -- Enable or disable the Promtail deployment.
  enabled: true
  image:
    repository: grafana/promtail
    tag: 2.9.2
    pullPolicy: IfNotPresent
  # -- Configuration for Promtail to discover and tail container logs.
  config:
    clients:
      - url: "" # This will be templated with the centralObservability.loki.lokiUrl
    snippets:
      pipelineStages:
        - docker: {}
      # This adds the `job` label to all logs, based on the k8s app label.
      relabeling:
        - source_labels: ["__meta_kubernetes_pod_label_app"]
          target_label: "job"
