// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/ClickHouse/clickhouse-go/v2"
	"github.com/google/wire"
	"github.com/hexabase/hexabase-ai/api/internal/api/handlers"
	"github.com/hexabase/hexabase-ai/api/internal/config"
	aiops3 "github.com/hexabase/hexabase-ai/api/internal/domain/aiops"
	application3 "github.com/hexabase/hexabase-ai/api/internal/domain/application"
	auth3 "github.com/hexabase/hexabase-ai/api/internal/domain/auth"
	backup2 "github.com/hexabase/hexabase-ai/api/internal/domain/backup"
	billing3 "github.com/hexabase/hexabase-ai/api/internal/domain/billing"
	cicd3 "github.com/hexabase/hexabase-ai/api/internal/domain/cicd"
	function3 "github.com/hexabase/hexabase-ai/api/internal/domain/function"
	logs3 "github.com/hexabase/hexabase-ai/api/internal/domain/logs"
	monitoring3 "github.com/hexabase/hexabase-ai/api/internal/domain/monitoring"
	node3 "github.com/hexabase/hexabase-ai/api/internal/domain/node"
	project3 "github.com/hexabase/hexabase-ai/api/internal/domain/project"
	workspace3 "github.com/hexabase/hexabase-ai/api/internal/domain/workspace"
	"github.com/hexabase/hexabase-ai/api/internal/helm"
	"github.com/hexabase/hexabase-ai/api/internal/repository/aiops"
	"github.com/hexabase/hexabase-ai/api/internal/repository/application"
	"github.com/hexabase/hexabase-ai/api/internal/repository/auth"
	"github.com/hexabase/hexabase-ai/api/internal/repository/backup"
	"github.com/hexabase/hexabase-ai/api/internal/repository/billing"
	"github.com/hexabase/hexabase-ai/api/internal/repository/cicd"
	"github.com/hexabase/hexabase-ai/api/internal/repository/function"
	kubernetes2 "github.com/hexabase/hexabase-ai/api/internal/repository/kubernetes"
	"github.com/hexabase/hexabase-ai/api/internal/repository/logs"
	"github.com/hexabase/hexabase-ai/api/internal/repository/monitoring"
	"github.com/hexabase/hexabase-ai/api/internal/repository/node"
	"github.com/hexabase/hexabase-ai/api/internal/repository/organization"
	"github.com/hexabase/hexabase-ai/api/internal/repository/project"
	"github.com/hexabase/hexabase-ai/api/internal/repository/proxmox"
	"github.com/hexabase/hexabase-ai/api/internal/repository/workspace"
	aiops2 "github.com/hexabase/hexabase-ai/api/internal/service/aiops"
	application2 "github.com/hexabase/hexabase-ai/api/internal/service/application"
	auth2 "github.com/hexabase/hexabase-ai/api/internal/service/auth"
	backup3 "github.com/hexabase/hexabase-ai/api/internal/service/backup"
	billing2 "github.com/hexabase/hexabase-ai/api/internal/service/billing"
	cicd2 "github.com/hexabase/hexabase-ai/api/internal/service/cicd"
	function2 "github.com/hexabase/hexabase-ai/api/internal/service/function"
	logs2 "github.com/hexabase/hexabase-ai/api/internal/service/logs"
	monitoring2 "github.com/hexabase/hexabase-ai/api/internal/service/monitoring"
	node2 "github.com/hexabase/hexabase-ai/api/internal/service/node"
	organization2 "github.com/hexabase/hexabase-ai/api/internal/service/organization"
	project2 "github.com/hexabase/hexabase-ai/api/internal/service/project"
	workspace2 "github.com/hexabase/hexabase-ai/api/internal/service/workspace"
	"gorm.io/gorm"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/metrics/pkg/client/clientset/versioned"
	"log/slog"
	"net/http"
	"time"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config, db *gorm.DB, k8sClient kubernetes.Interface, dynamicClient dynamic.Interface, k8sConfig *rest.Config, logger *slog.Logger) (*App, error) {
	repository := application.NewPostgresRepository(db)
	versionedInterface, err := ProvideMetricsClientset(k8sConfig)
	if err != nil {
		return nil, err
	}
	kubernetesRepository := application.NewKubernetesRepository(k8sClient, versionedInterface)
	service := application2.NewService(repository, kubernetesRepository)
	applicationHandler := handlers.NewApplicationHandler(service)
	authRepository := auth.NewPostgresRepository(db)
	v := ProvideOAuthProviderConfigs(cfg)
	oAuthRepository := auth.NewOAuthRepository(v)
	keyRepository, err := auth.NewKeyRepository()
	if err != nil {
		return nil, err
	}
	authService := auth2.NewService(authRepository, oAuthRepository, keyRepository, logger)
	authHandler := handlers.NewAuthHandler(authService, logger)
	backupRepository := backup.NewPostgresRepository(db)
	proxmoxRepository := ProvideBackupProxmoxRepository(cfg)
	workspaceRepository := workspace.NewPostgresRepository(db)
	backupService := ProvideBackupService(backupRepository, proxmoxRepository, repository, workspaceRepository, k8sClient, cfg)
	backupHandler := handlers.NewBackupHandler(backupService)
	billingRepository := billing.NewPostgresRepository(db)
	stripeAPIKey := ProvideStripeAPIKey(cfg)
	stripeWebhookSecret := ProvideStripeWebhookSecret(cfg)
	stripeRepository := ProvideStripeRepository(stripeAPIKey, stripeWebhookSecret)
	billingService := billing2.NewService(billingRepository, stripeRepository, logger)
	billingHandler := handlers.NewBillingHandler(billingService, logger)
	monitoringRepository := monitoring.NewPostgresRepository(db)
	repository2 := kubernetes2.NewKubernetesRepository(k8sClient)
	monitoringService := monitoring2.NewService(monitoringRepository, repository2, logger)
	monitoringHandler := handlers.NewMonitoringHandler(monitoringService, logger)
	postgresRepository := node.NewPostgresRepository(db)
	nodeRepository := ProvideNodeRepository(postgresRepository)
	nodeProxmoxRepository := ProvideProxmoxRepository(cfg)
	proxmoxRepository2 := ProvideProxmoxRepositoryInterface(nodeProxmoxRepository)
	nodeService := node2.NewService(nodeRepository, proxmoxRepository2)
	service2 := ProvideNodeService(nodeService)
	nodeHandler := handlers.NewNodeHandler(service2, logger)
	organizationRepository := organization.NewPostgresRepository(db)
	organizationAuthRepository := organization.NewAuthRepositoryAdapter(authRepository)
	organizationBillingRepository := organization.NewBillingRepositoryAdapter(stripeRepository)
	organizationService := organization2.NewService(organizationRepository, organizationAuthRepository, organizationBillingRepository, logger)
	organizationHandler := handlers.NewOrganizationHandler(organizationService, logger)
	projectRepository := project.NewPostgresRepository(db)
	projectKubernetesRepository := project.NewKubernetesRepository(k8sClient, dynamicClient, k8sConfig)
	projectService := project2.NewService(projectRepository, projectKubernetesRepository, logger)
	projectHandler := handlers.NewProjectHandler(projectService, logger)
	workspaceKubernetesRepository := workspace.NewKubernetesRepository(k8sClient, dynamicClient, k8sConfig)
	workspaceAuthRepository := workspace.NewAuthRepositoryAdapter(authRepository)
	helmService := helm.NewService(k8sConfig, logger)
	workspaceService := workspace2.NewService(workspaceRepository, workspaceKubernetesRepository, workspaceAuthRepository, helmService, logger)
	workspaceHandler := handlers.NewWorkspaceHandler(workspaceService, logger)
	cicdRepository := cicd.NewPostgresRepository(db)
	cicdNamespace := ProvideCICDNamespace()
	providerFactory := ProvideCICDProviderFactory(k8sClient, k8sConfig, cicdNamespace)
	credentialManager := ProvideCICDCredentialManager(k8sClient, cicdNamespace)
	cicdService := cicd2.NewService(cicdRepository, providerFactory, credentialManager, logger)
	cicdHandler := handlers.NewCICDHandler(cicdService, logger)
	sqlDB, err := ProvideSQLDB(db)
	if err != nil {
		return nil, err
	}
	functionPostgresRepository := function.NewPostgresRepository(sqlDB)
	functionRepository := ProvideFunctionRepository(functionPostgresRepository)
	functionProviderFactory := ProvideFunctionProviderFactory(k8sClient, dynamicClient)
	functionService := function2.NewService(functionRepository, functionProviderFactory, logger)
	service3 := ProvideFunctionService(functionService)
	functionHandler := handlers.NewFunctionHandler(service3, logger)
	aiOpsProxyHandler, err := ProvideAIOpsProxyHandler(authService, logger, cfg)
	if err != nil {
		return nil, err
	}
	v2, err := ProvideClickHouseConnection(cfg)
	if err != nil {
		return nil, err
	}
	logsRepository := logs.NewClickHouseRepository(v2)
	logsService := logs2.NewLogService(logsRepository, logger)
	llmService := ProvideOllamaService(cfg)
	aiopsRepository := aiops.NewPostgresRepository(db)
	aiopsService := aiops2.NewService(llmService, aiopsRepository, logger)
	internalHandler := ProvideInternalHandler(workspaceService, projectService, service, service2, logsService, monitoringService, aiopsService, cicdService, backupService, logger)
	app := NewApp(applicationHandler, authHandler, backupHandler, billingHandler, monitoringHandler, nodeHandler, organizationHandler, projectHandler, workspaceHandler, cicdHandler, functionHandler, aiOpsProxyHandler, internalHandler)
	return app, nil
}

// wire.go:

var ApplicationSet = wire.NewSet(application.NewPostgresRepository, application.NewKubernetesRepository, application2.NewService, handlers.NewApplicationHandler)

var AuthSet = wire.NewSet(auth.NewPostgresRepository, auth.NewOAuthRepository, auth.NewKeyRepository, auth2.NewService, handlers.NewAuthHandler)

var BackupSet = wire.NewSet(backup.NewPostgresRepository, ProvideBackupProxmoxRepository,
	ProvideBackupService, handlers.NewBackupHandler,
)

var BillingSet = wire.NewSet(billing.NewPostgresRepository, ProvideStripeRepository, billing2.NewService, handlers.NewBillingHandler)

var MonitoringSet = wire.NewSet(monitoring.NewPostgresRepository, kubernetes2.NewKubernetesRepository, monitoring2.NewService, handlers.NewMonitoringHandler)

var NodeSet = wire.NewSet(node.NewPostgresRepository, ProvideNodeRepository, ProvideProxmoxRepository, ProvideProxmoxRepositoryInterface, node2.NewService, ProvideNodeService, handlers.NewNodeHandler)

var OrganizationSet = wire.NewSet(organization.NewPostgresRepository, organization.NewAuthRepositoryAdapter, organization.NewBillingRepositoryAdapter, organization2.NewService, handlers.NewOrganizationHandler)

var ProjectSet = wire.NewSet(project.NewPostgresRepository, project.NewKubernetesRepository, project2.NewService, handlers.NewProjectHandler)

var WorkspaceSet = wire.NewSet(workspace.NewPostgresRepository, workspace.NewKubernetesRepository, workspace.NewAuthRepositoryAdapter, workspace2.NewService, handlers.NewWorkspaceHandler)

var CICDSet = wire.NewSet(cicd.NewPostgresRepository, ProvideCICDProviderFactory, ProvideCICDCredentialManager, cicd2.NewService, handlers.NewCICDHandler)

var FunctionSet = wire.NewSet(
	ProvideSQLDB, function.NewPostgresRepository, ProvideFunctionRepository,
	ProvideFunctionProviderFactory, function2.NewService, ProvideFunctionService, handlers.NewFunctionHandler,
)

var HelmSet = wire.NewSet(helm.NewService)

var AIOpsProxySet = wire.NewSet(
	ProvideAIOpsProxyHandler,
)

var AIOpsSet = wire.NewSet(aiops.NewPostgresRepository, ProvideOllamaService, aiops2.NewService)

var LogSet = wire.NewSet(ProvideClickHouseConnection, logs.NewClickHouseRepository, logs2.NewLogService)

var InternalSet = wire.NewSet(ProvideInternalHandler)

type App struct {
	ApplicationHandler  *handlers.ApplicationHandler
	AuthHandler         *handlers.AuthHandler
	BackupHandler       *handlers.BackupHandler
	BillingHandler      *handlers.BillingHandler
	MonitoringHandler   *handlers.MonitoringHandler
	NodeHandler         *handlers.NodeHandler
	OrganizationHandler *handlers.OrganizationHandler
	ProjectHandler      *handlers.ProjectHandler
	WorkspaceHandler    *handlers.WorkspaceHandler
	CICDHandler         *handlers.CICDHandler
	FunctionHandler     *handlers.FunctionHandler
	AIOpsProxyHandler   *handlers.AIOpsProxyHandler
	InternalHandler     *handlers.InternalHandler
}

func NewApp(appH *handlers.ApplicationHandler, authH *handlers.AuthHandler, backupH *handlers.BackupHandler, billH *handlers.BillingHandler, monH *handlers.MonitoringHandler, nodeH *handlers.NodeHandler, orgH *handlers.OrganizationHandler, projH *handlers.ProjectHandler, workH *handlers.WorkspaceHandler, cicdH *handlers.CICDHandler, funcH *handlers.FunctionHandler, aiopsH *handlers.AIOpsProxyHandler, internalHandler *handlers.InternalHandler) *App {
	return &App{ApplicationHandler: appH, AuthHandler: authH, BackupHandler: backupH, BillingHandler: billH, MonitoringHandler: monH, NodeHandler: nodeH, OrganizationHandler: orgH, ProjectHandler: projH, WorkspaceHandler: workH, CICDHandler: cicdH, FunctionHandler: funcH, AIOpsProxyHandler: aiopsH, InternalHandler: internalHandler}
}

type StripeAPIKey string

type StripeWebhookSecret string

type AIOpsServiceURL string

type CICDNamespace string

type BackupEncryptionKey string

func ProvideOAuthProviderConfigs(cfg *config.Config) map[string]*auth.ProviderConfig {
	providers := make(map[string]*auth.ProviderConfig)
	if cfg.Auth.ExternalProviders == nil {
		return providers
	}
	for name, p := range cfg.Auth.ExternalProviders {
		providers[name] = &auth.ProviderConfig{
			ClientID:     p.ClientID,
			ClientSecret: p.ClientSecret,
			RedirectURL:  p.RedirectURL,
			Scopes:       p.Scopes,
			AuthURL:      p.AuthURL,
			TokenURL:     p.TokenURL,
		}
	}
	return providers
}

func ProvideStripeAPIKey(cfg *config.Config) StripeAPIKey { return StripeAPIKey(cfg.Stripe.APIKey) }

func ProvideStripeWebhookSecret(cfg *config.Config) StripeWebhookSecret {
	return StripeWebhookSecret(cfg.Stripe.WebhookSecret)
}

func ProvideAIOpsServiceURL(cfg *config.Config) (AIOpsServiceURL, error) {
	if cfg.AIOps.URL != "" {
		return AIOpsServiceURL(cfg.AIOps.URL), nil
	}
	return AIOpsServiceURL("http://ai-ops-service.ai-ops.svc.cluster.local:8000"), nil
}

func ProvideStripeRepository(apiKey StripeAPIKey, webhookSecret StripeWebhookSecret) billing3.StripeRepository {
	return billing.NewStripeRepository(string(apiKey), string(webhookSecret))
}

func ProvideCICDNamespace() CICDNamespace { return CICDNamespace("hexabase-cicd") }

func ProvideCICDProviderFactory(kubeClient kubernetes.Interface, k8sConfig *rest.Config, namespace CICDNamespace) cicd3.ProviderFactory {
	return cicd.NewProviderFactory(kubeClient, k8sConfig, string(namespace))
}

func ProvideCICDCredentialManager(kubeClient kubernetes.Interface, namespace CICDNamespace) cicd3.CredentialManager {
	return cicd.NewKubernetesCredentialManager(kubeClient, string(namespace))
}

func ProvideFunctionProviderFactory(kubeClient kubernetes.Interface, dynamicClient dynamic.Interface) function3.ProviderFactory {
	return function.NewProviderFactory(kubeClient, dynamicClient)
}

func ProvideFunctionService(service *function2.Service) function3.Service {
	return service
}

func ProvideSQLDB(gormDB *gorm.DB) (*sql.DB, error) {
	return gormDB.DB()
}

func ProvideFunctionRepository(repo *function.PostgresRepository) function3.Repository {
	return repo
}

func ProvideClickHouseConnection(cfg *config.Config) (clickhouse.Conn, error) {

	conn, err := clickhouse.Open(&clickhouse.Options{
		Addr: []string{cfg.ClickHouse.Address},
	})
	if err != nil {
		return nil, err
	}
	return conn, nil
}

func ProvideProxmoxRepository(cfg *config.Config) *node.ProxmoxRepository {

	httpClient := &http.Client{
		Timeout: 30 * time.Second,
	}
	return node.NewProxmoxRepository(httpClient, "https://proxmox.example.com/api2/json", "your-api-token")
}

func ProvideMetricsClientset(k8sConfig *rest.Config) (versioned.Interface, error) {
	return versioned.NewForConfig(k8sConfig)
}

func ProvideNodeService(svc *node2.Service) node3.Service {
	return svc
}

func ProvideNodeRepository(repo *node.PostgresRepository) node3.Repository {
	return repo
}

func ProvideProxmoxRepositoryInterface(repo *node.ProxmoxRepository) node3.ProxmoxRepository {
	return repo
}

func ProvideBackupProxmoxRepository(cfg *config.Config) backup2.ProxmoxRepository {

	client := proxmox.NewClient("https://proxmox.example.com/api2/json", "root@pam", "tokenID", "tokenSecret")
	return backup.NewProxmoxRepository(client)
}

func ProvideBackupService(
	repo backup2.Repository,
	proxmoxRepo backup2.ProxmoxRepository,
	appRepo application3.Repository,
	workspaceRepo workspace3.Repository,
	k8sClient kubernetes.Interface,
	cfg *config.Config,
) backup2.Service {

	encryptionKey := "your-backup-encryption-key"
	return backup3.NewService(repo, proxmoxRepo, appRepo, workspaceRepo, k8sClient, encryptionKey)
}

func ProvideAIOpsProxyHandler(authSvc auth3.Service, logger *slog.Logger, cfg *config.Config) (*handlers.AIOpsProxyHandler, error) {
	var aiopsURL string
	if cfg.AIOps.URL != "" {
		aiopsURL = cfg.AIOps.URL
	} else {
		aiopsURL = "http://ai-ops-service.ai-ops.svc.cluster.local:8000"
	}
	return handlers.NewAIOpsProxyHandler(authSvc, logger, aiopsURL)
}

func ProvideOllamaService(cfg *config.Config) aiops3.LLMService {

	ollamaURL := "http://ollama.ollama.svc.cluster.local:11434"
	timeout := 30 * time.Second
	headers := make(map[string]string)
	return aiops.NewOllamaProvider(ollamaURL, timeout, headers)
}

func ProvideInternalHandler(
	workspaceSvc workspace3.Service,
	projectSvc project3.Service,
	applicationSvc application3.Service,
	nodeSvc node3.Service,
	logSvc logs3.Service,
	monitoringSvc monitoring3.Service,
	aiopsSvc aiops3.Service,
	cicdSvc cicd3.Service,
	backupSvc backup2.Service,
	logger *slog.Logger,
) *handlers.InternalHandler {
	return handlers.NewInternalHandler(
		workspaceSvc,
		projectSvc,
		applicationSvc,
		nodeSvc,
		logSvc,
		monitoringSvc,
		aiopsSvc,
		cicdSvc,
		backupSvc,
		logger,
	)
}
