apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-attestations
  annotations:
    policies.kyverno.io/title: Verify Image Attestations
    policies.kyverno.io/category: Software Supply Chain Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy verifies that container images have specific attestations
      such as vulnerability scan results and SBOM (Software Bill of Materials).
spec:
  validationFailureAction: Audit
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Ignore
  rules:
    - name: check-vulnerability-scan
      match:
        any:
        - resources:
            kinds:
            - Pod
            namespaceSelector:
              matchLabels:
                hexabase.ai/require-attestations: "true"
      verifyImages:
      - imageReferences:
        - "*"
        attestations:
        - type: "https://cosign.sigstore.dev/attestation/vuln/v1"
          attestors:
          - count: 1
            entries:
            - keys:
                publicKeys: |-
                  -----BEGIN PUBLIC KEY-----
                  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7Q9Y1YpQXq1a
                  1M5r0L8v2PM3UJrfVmZ6FQojE0H8gVLl/FUpqBj/rJT1wkor
                  x1Yx5BA5fmFvQVmH7JgmHZLvtQ==
                  -----END PUBLIC KEY-----
          conditions:
          - all:
            - key: "{{ vulnerabilities.critical }}"
              operator: Equals
              value: "0"
            - key: "{{ vulnerabilities.high }}"
              operator: LessThanOrEquals
              value: "5"